### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by Keats** [Gilnaa/globwalk#1]
I just tried `globwalk` after reading https://github.com/Keats/tera/issues/212 and the globset PR associated.

First: the example in the README does not compile.

Second, I think an API like this would be nicer:

```rust
// not going to actually write the code
struct GlobWalk {}

impl GlobWalk {
 // takes a single pattern and assume current  dir -> like `glob` and the python `glob` (https://docs.python.org/3/library/glob.html)
  pub fn new(pat: &str) -> Result<Self, Error> {}

  // same as current one, minus the base directory
  pub fn from_patterns(pat: &[S]) -> Result<Self, Error> {}

  pub base_directory(&mut self, dir: &str) -> Self {}

 // rest of the builder similar to currently
}
```

The main advantage with that API is simplicity for the common case: find everything matching in a single given pattern for the cwd. This is how `glob` works in pretty much every languages I know (including Rust) and that would be weird to change that.
I see "glob searches for files in the current working directory, whereas globwalk starts at a specified base-dir." in the README but doesn't really explain why.

I'd be happy to implement that in a PR if you agree.

**Comment by Gilnaa** [comment]
I'd love to, that sounds great.

I guess I like to be able to specify the base dir because I want to avoid hidden, global, state.

**Comment by Gilnaa** [comment]
API changed

**Comment by Keats** [comment]
Ah sorry I didn't find the time to work on it as well. Something to consider as well that afaik is not there currently is to use the pattern when there is only one to determine the base like `glob` does. So `GlobWalker::new("music/albums/*.{mp3,flac}")`  would set the base to "music/albums` rather than `.`, avoiding to walk potentially lots of directories/files.

I think having a `glob(pat: &str)` fn that is just a call to `GlobWalker::new(pat)` internally would be a nice UX touch as well.

**Comment by Gilnaa** [comment]
No worries :)

It is important as an optimization, I'll add it sometime.
I would rather add a more general optimization, but I don't have time to figure out how to do that.

Can't say I feel one way or the other about the `glob` fn, is it something to do with API parity with the glob crate?

**Comment by Keats** [comment]
> Can't say I feel one way or the other about the glob fn, is it something to do with API parity with the glob crate?

Yes, in most languages `glob` is a simple fn and I expect the majority of people to be using only that. No need to expose a struct if it's not needed for the common case.

**Comment by Gilnaa** [comment]
Yeah, that makes sense
