### ISSUE TITLE
Does not work on absolute paths

### ISSUE THREAD

**Issue by sunjay** [Gilnaa/globwalk#18]
Hi, I ran into a surprizing error today. I was using the `tera` template engine (which depends on `globwalk`), and I couldn't get it to load my templates. It turns out that while the `glob` crate works with absolute paths, `globwalk` does not. I was using the `glob` crate in addition to `tera` and was very confused about why this wasn't working.

I made this simple example program to demonstrate:

```rust
use std::fs::canonicalize;

use globwalk::glob;

fn main() {
    let relpattern = "src/*.rs";
    println!("With relative path: {}", relpattern);
    for file in glob(relpattern).unwrap() {
        println!("{:?}", file.unwrap());
    }

    let abspath = canonicalize("src").unwrap().join("*.rs");
    let abspath = abspath.to_str().unwrap();
    println!("With absolute path: {}", abspath);
    for file in glob(abspath).unwrap() {
        println!("{:?}", file.unwrap());
    }
}
```

This produces the following output:

```
With relative path: src/*.rs
DirEntry("./src/main.rs")
With absolute path: /tmp/glob-bug/src/*.rs
```

As you can see, with the relative path, it prints the correct entires. However, with the absolute path, nothing is printed at all.

**Comment by Gilnaa** [comment]
I wrote this patch https://github.com/Gilnaa/globwalk/pull/19 which should fix this.
Would you mind testing this with Tera before I merge it?

**Comment by Keats** [comment]
I've added a test in Tera for absolute globbing and the patch does fix it

**Comment by Gilnaa** [comment]
Version 0.6.0 fixes this
