### ISSUE TITLE
globwalk exposes `globset::Error` in its API

### ISSUE THREAD

**Issue by epage** [Gilnaa/globwalk#2]
This forces clients to directly depend on globset just for error handling.

I'm working on a CLI test utility for easily populating a temp dir and am looking at using globwalk because it implements "good enough" policy to expose in a simple API.  Ran into this when integrating globwalk.

**Comment by Gilnaa** [comment]
What would like to see instead?

**Comment by epage** [comment]
My thought is to either re-export globsets error or a globwalk-specific error type that wraps globsets.

**Comment by Gilnaa** [comment]
You got it
