### ISSUE TITLE
Directory Walk Order Quesiton

### ISSUE THREAD

**Issue by jmwright** [Gilnaa/globwalk#20]
In Ubuntu 18.04, Windows and MacOS the directories are walked in the same order when I run this code:
```rust
let target_dir = Path::from("/tmp/temp_356d21aa-5320-4fc1-a6db-e47b28ed2a94/toplevel/");
let walker = globwalk::GlobWalkerBuilder::from_patterns(target_dir, &[".sr"])
        .max_depth(100)
        .follow_links(false)
        .build()
        .expect("Could not build globwalk directory walker.")
        .into_iter()
        .filter_map(Result::ok);

for sr_file in walker {
    println!("{:?}", sr_file);
}
```
Here is the order:.
```
"/tmp/temp_356d21aa-5320-4fc1-a6db-e47b28ed2a94/toplevel/.sr"
"/tmp/temp_356d21aa-5320-4fc1-a6db-e47b28ed2a94/toplevel/components/level1/.sr"
"/tmp/temp_356d21aa-5320-4fc1-a6db-e47b28ed2a94/toplevel/components/level1/components/level2/.sr"
"/tmp/temp_356d21aa-5320-4fc1-a6db-e47b28ed2a94/toplevel/components/level1/components/level2/components/level3/.sr"
"/tmp/temp_356d21aa-5320-4fc1-a6db-e47b28ed2a94/toplevel/node_modules/blink_firmware/.sr"
```
However, running the same code in Travis CI (which I think still uses Ubuntu 14.04 by default) or on Manjaro Linux (Arch Linux based) gives a different order:
```
"/tmp/temp_de230ca5-121e-4293-98f3-c599b83f18ed/toplevel/node_modules/blink_firmware/.sr"
"/tmp/temp_de230ca5-121e-4293-98f3-c599b83f18ed/toplevel/.sr"
"/tmp/temp_de230ca5-121e-4293-98f3-c599b83f18ed/toplevel/components/level1/.sr"
"/tmp/temp_de230ca5-121e-4293-98f3-c599b83f18ed/toplevel/components/level1/components/level2/.sr"
"/tmp/temp_de230ca5-121e-4293-98f3-c599b83f18ed/toplevel/components/level1/components/level2/components/level3/.sr"
```
I'm assuming that the difference is based on which libraries are used on the systems, but I'm not sure. Is there a way to enforce the same sort, regardless of what system the code is running on?

**Comment by Gilnaa** [comment]
What about sort_by?

https://docs.rs/globwalk/0.6.0/globwalk/struct.GlobWalkerBuilder.html#method.sort_by

**Comment by jmwright** [comment]
@Gilnaa Thanks for the response.

I tried using sort_by to sort based on number of segments in the path to get a top-down sort, but then it seems like there needs to be a lexical sort within that to make sure the sort is always the same. I can't see how sort_by would do a dual sort.

**Comment by jmwright** [comment]
It's a hack, but I ended up converting to the paths to lossy strings and then doing a comparison on the strings. It works across Windows, MacOS and the 3 Linux distros I've tried so far. Someone can feel free to post this back here with a better solution, but for now I'm going to close this.
