### ISSUE TITLE
"Why not glob" entry misleading?

### ISSUE THREAD

**Issue by jayvdb** [Gilnaa/globwalk#35]
> glob searches for files in the current working directory, whereas globwalk starts at a specified base-dir.

Both seem to default to the current directory for their simplest API, and both have the option of using an absolute path.
e.g. 
```rust
for entry in glob::glob("/media/**/*.jpg")
```

**Comment by Gilnaa** [comment]
IIRC this was written 6 years ago, before the current incarnation of the glob crate.
I am not sure there is any reason to use this crate over glob in modern times, I'll have to research this at some point, maybe recommend just using glob.

**Comment by Gilnaa** [comment]
It looks like there are a few options that are not available in `glob`, like limiting depth, filtering by file type, etc.
I'll update the readme to point out these differences and recommend just using `glob` unless they're absolutely needed.

**Comment by Gilnaa** [comment]
On second thought, and seeing this [still-open-issue](https://github.com/rust-lang/glob/issues/54), it occurs to me that the significance is that you're able to set the directory without changing the glob pattern itself.

**Comment by Gilnaa** [comment]
After much thought, and in light of the linked glob issue, I think I'll keep this sentence.
I have, however, rewritten parts of the `README.md` to recommend new users to just use `glob` instead.

Thank you!
